# 编辑好的图片路径 Image path
IMAGE_PATH: "./image/image_monitor.png"

# 串口号 Communication port
COM_PORT: "COM33"

# 比特率 Baud rate
COM_BAUDRATE: 9600

# Android 多点触控数量 Multi-touch amount
MAX_SLOT: 12

# 检测区域的像素值范围 Detection area size (Pixel)
AREA_SCOPE: 70

# 检测区域圆上点的数量 Amount of points in detection area
AREA_POINT_NUM: 8

# Android 设备实际屏幕大小（单位:像素）Actual screen dimensions (Pixel)
ANDROID_ABS_MONITOR_SIZE: [ 1800, 2880 ]

# Android 设备触控屏幕大小（单位:像素）Touch screen dimensions (Pixel)
ANDROID_ABS_INPUT_SIZE: [ 18000, 28800 ]

# 是否开启屏幕反转（充电口朝上时开启该配置）Rotate the screen 180 degree (Default face charging port)
ANDROID_REVERSE_MONITOR: false

# touch_thread 是否启用 sleep, 默认关闭, 如果程序 CPU 占用较高则开启, 如果滑动时延迟极大请关闭 Sleep mode (Turn on if you think the CPU usage is too high, turn off if you feel swipe is delayed)
TOUCH_THREAD_SLEEP_MODE: false

# 每次 sleep 的延迟, 单位: 微秒, 默认 100 微秒 Sleep delay ms (Default: 100)
TOUCH_THREAD_SLEEP_DELAY: 50

# 当需要指定触控设备时填上使用 “adb devices” 获取到的设备序列号，留空则只支持单设备连接 Specify adb devices (Use if you have mulitple, other wise leave if empty)
SPECIFIED_DEVICES: ""

# RGB 颜色值对应区块配置（不建议更改）RGB color detection settings (Not recommended to change)
exp_image_dict:
  '41-65-93': A1
  '87-152-13': A2
  '213-109-81': A3
  '23-222-55': A4
  '69-203-71': A5
  '147-253-55': A6
  '77-19-35': A7
  '159-109-79': A8
  '87-217-111': B1
  '149-95-154': B2
  '97-233-9': B3
  '159-27-222': B4
  '152-173-186': B5
  '192-185-149': B6
  '158-45-23': B7
  '197-158-219': B8
  '127-144-79': C1
  '242-41-155': C2
  '69-67-213': D1
  '105-25-130': D2
  '17-39-170': D3
  '97-103-203': D4
  '113-25-77': D5
  '21-21-140': D6
  '155-179-166': D7
  '55-181-134': D8
  '61-33-27': E1
  '51-91-95': E2
  '143-227-63': E3
  '216-67-226': E4
  '202-181-245': E5
  '99-11-183': E6
  '75-119-224': E7
  '182-19-85': E8
